# Generated by Django 3.0.7 on 2020-06-29 04:18

from django.db import migrations, models
import forum.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=forum.models.user.user_directory_avatar),
        ),
    ]
