# Generated by Django 3.0.7 on 2020-06-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
    ]
