# Generated by Django 3.0.7 on 2020-07-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='authToken',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='refreshToken',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
