# Generated by Django 3.0.7 on 2020-07-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_userprofile_last_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='authToken',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='refreshToken',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='private_key',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
