# Generated by Django 3.0.7 on 2020-07-11 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
