# Generated by Django 3.0.7 on 2020-07-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20200711_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
