# Generated by Django 3.0.7 on 2020-07-24 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20200720_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='name',
            new_name='title',
        ),
    ]
