# Generated by Django 3.0.7 on 2020-08-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20200724_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='nPost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forum',
            name='nThread',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='nPost',
            field=models.IntegerField(default=0),
        ),
    ]
