# Generated by Django 3.0.7 on 2020-08-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_auto_20200806_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='nView',
            field=models.IntegerField(default=0),
        ),
    ]
